import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import Footer from "./(root)/_components/footer";
import AuthLayout from "./(auth)/layout";
import AuthContextProvider from "./(root)/admin/_components/auth-provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthContextProvider>
      <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            <main>
            <AuthLayout>
              {children}
            </AuthLayout>
            </main>
            <Footer/>
          </body>
        </html>
      </ClerkProvider>
    </AuthContextProvider>
  );
}
